yolo_detector_node:
  ros__parameters:
    image_topic: "/robot1/color/image_raw"
    model_path: "models/yolo/city_cv_yolo11n_best.pt"
    inference_period_sec: 2.0
    confidence_threshold: 0.5
    imgsz: 640
    device: "0"
    publish_annotated_image: true
    enable_yolo: true
    show_yolo_window: true
